### ISSUE TITLE
[Bug]: hulk smash! advancement can be obtained without using a hulk hammer

### ISSUE THREAD

**Issue by asweqr** [Fuzss/mutantmonsters#23] opened 2023-06-28 04:12 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

7.0.0

### Notes (Required)

1 knock out a mutant zombie with normal weapons EG sword
2 set the mutant zombie on fire
3 mutant zombie dies
4 player is given the hulk smash advancement dispite not useing a hulk hammer

Extra Note
it might also happen on other versions like 1.18.2 forge and most likely other versions

https://github.com/Fuzss/mutantmonsters/assets/89364836/0a85e269-9341-4c75-88c9-89f149784d87

**Comment by Fuzss** [comment] 2023-07-02 06:15
Fixed in v8.0.5. Will backport at some point to other supported MC versions.

Just a note though: The advancement is a bit broken by design, meaning it triggers when simply holding a hulk hammer and a mutant zombie dies. The bug you experienced no longer happens, but it can still be cheesed by just switching your main hand item. Due to how the death mechanic of the zombie works this can't be easily solved it seems like and I don't care too much about the advancements to dedicated much time to it.

**Closed by Fuzss** 2023-07-02 06:15 UTC
Labels: bug

**Comment by Aceplante2** [comment] 2023-12-02 18:02
Still an issue on 1.19.2
